const {
    pluginTypescript,
    parserTypescript,
    configAlloy,
    configGitignore,
    pluginImport,
    pluginReact,
    pluginReactHooks,
    pluginVue,
    pluginImportResolverNode,
    pluginImportResolverTypescript,
    globals,
    localPkg,
    parserVue,
} = require("./modules.cjs");

module.exports = {
    pluginTypescript,
    parserTypescript,
    configAlloy,
    configGitignore,
    pluginImport,
    pluginReact,
    pluginReactHooks,
    pluginVue,
    pluginImportResolverNode,
    pluginImportResolverTypescript,
    globals,
    localPkg,
    parserVue,
};
